### ISSUE TITLE
Free Shipping Banner - "Some Restrictions Apply" Link Does Not Work

### ISSUE THREAD

**Issue by chrisatnwca** [DerekFoulk/nwca-nitrosell#81] opened 2015-07-30 23:07 UTC
"Some restrictions apply" - clicking the link in banner updates the URL to "/#freeshipping" but provides no information.

![free shipping link](https://cloud.githubusercontent.com/assets/13579289/8997324/e925f996-36d4-11e5-9524-7b920a8f53d6.png)

**Comment by DerekFoulk** [comment] 2015-07-31 20:26
Issue is caused by the fact that there is no modal present for the link to open. Issue is being resolved...

**Comment by DerekFoulk** [comment] 2015-07-31 21:22
Issue was resolved with the release of 0a31dae.

**Closed by DerekFoulk** 2015-07-31 21:22 UTC
Labels: Bug
